### ISSUE TITLE
横屏扫描摄像头方向有问题

### ISSUE THREAD

**Issue by wh930201** [lcddhr/QRWeiXinDemo#1]
我用ipad横屏扫描时 摄像头的方向仍然为竖屏

**Comment by lcddhr** [comment]
@wh930201 

暂时只支持竖屏哦，有空我会改的

**Comment by kongxiangkuang** [comment]
自己想去 解决ipad横屏问题，毫无头绪 求教。。。。

**Comment by lcddhr** [comment]
@kongxiangkuang 手上没有iPad设备 ，手机测试了一下横屏，可以扫描。麻烦看看iPad上能用么，不行我再想办法周日拿一个iPad过来测

**Comment by lcddhr** [comment]
@wh930201 手上没有iPad设备 ，手机测试了一下横屏，可以扫描。麻烦看看iPad上能用么，不行我再想办法周日拿一个iPad过来测

**Comment by kongxiangkuang** [comment]
时间有点久了 我都忘记我怎么改的。好像只是 ui界面 没适配好 我就直接锁成横屏 然后调整了下扫描区域
