### ISSUE TITLE
你好，为什么扫描二维码没有任何反应啊？

### ISSUE THREAD

**Issue by zj0517** [lcddhr/QRWeiXinDemo#2]
你好，我的测试设备是Iphone 6 系统是iOS 8.4 Xcode用的6.4 调成横屏可以扫描成功，你的demo真机也可以运行成功了，但是加入到我的测试项目中却报错了，截图给你看看！麻烦帮忙看一下怎么回事？
<img width="978" alt="qq20151013-1 2x" src="https://cloud.githubusercontent.com/assets/10892710/10449839/be03fc3e-71c8-11e5-87a2-115720b6762e.png">

**Comment by lcddhr** [comment]
@zj0517 请问你是用什么设备测试的呢，还有系统

**Comment by lcddhr** [comment]
@zj0517 这句代码是写在设置完`input`和`output`之后吗？

**Comment by zj0517** [comment]
是的啊，直接Copy你的demo代码，没有一点改动的，就是报错，目前还是没有解决！

**Comment by lcddhr** [comment]
@zj0517 能发个demo上来么

**Comment by zj0517** [comment]
找到解决问题的办法了，是因为相机的访问权限没有判断，如果打开相机的访问权限一切都OK了！

**Comment by lcddhr** [comment]
@zj0517 好的，还有其他问题么

**Comment by zj0517** [comment]
没有了，楼主加个相机的访问权限判断进去，不然像我这样小白看代码一模一样找了半天错误也不知道怎么回事，还有你的这个二维码做的不错！感谢你的分享！
