### ISSUE TITLE
扫描二维码后跳转到新的界面再返回 为啥屏幕还一直停留在之前扫到过的二维码的界面？这要怎么改呢？

### ISSUE THREAD

**Issue by xjcristal** [lcddhr/QRWeiXinDemo#3]
![f16e15955deb42aa7c0849f9e03a4bcc](https://cloud.githubusercontent.com/assets/11403491/10604579/db50d502-7757-11e5-992f-db30778cf50d.png)

**Comment by lcddhr** [comment]
@xjcristal 可以了,代码在这里[#4](https://github.com/lcddhr/QRWeiXinDemo/pull/4)
