### ISSUE TITLE
能扫描相册里的二维码？

### ISSUE THREAD

**Issue by iHTCboy** [lcddhr/QRWeiXinDemo#5]
能扫描相册里的二维码吗？暂时没想到，或者给我一个思路吧，谢谢！！

**Comment by lcddhr** [comment]
@iHTCboy [这里](https://github.com/lcddhr/QRWeiXinDemo/commit/511d4ef2d0b8385e2672599af614ed96da9e33b1)，刚刚上传了读取二维码图片的代码，长按二维码可以获取URL。下载测试一下，不过要iOS8之后才能测试，模拟器的话用5s之后的机子

**Comment by iHTCboy** [comment]
好的，谢谢，我下周上班在试试。但不明白，为什么要iOS8才可以？

**Comment by lcddhr** [comment]
@iHTCboy 因为读取用到了`CIDetectorTypeQRCode`，这个是iOS8之后才有的。如果要兼容iOS7估计得用ZXing了,但是ZXing会有bug,有些二维码会读取不了，所以要权衡一下吧

**Comment by iHTCboy** [comment]
好的，谢谢啦！！
