### ISSUE TITLE
判断相机方法有误

### ISSUE THREAD

**Issue by iHTCboy** [lcddhr/QRWeiXinDemo#6]
- (BOOL)validateCamera {
  
  return [UIImagePickerController isSourceTypeAvailable:UIImagePickerControllerSourceTypeCamera] &&
         [UIImagePickerController isCameraDeviceAvailable:UIImagePickerControllerCameraDeviceRear];
  }

以面方法是判断相册的权限哦。

**Comment by lcddhr** [comment]
@iHTCboy `UIImagePickerControllerSourceTypeCamera`这里判断的是相机

**Comment by iHTCboy** [comment]
@lcddhr 在iOS 9.1下如果原来拒绝访问相机，那个判断没有起作用，还是能点击进二维码但取不到画面所以就崩溃了。

**Comment by lcddhr** [comment]
@iHTCboy 感谢反馈，已经加上。详情在[这里](https://github.com/lcddhr/QRWeiXinDemo/commit/c9bc4dc35f483df10e8845e3266057f04026664f)
